# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='qw', max_length=255),
            preserve_default=False,
        ),
    ]
