# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(verbose_name='текст')),
                ('foto_befo', models.ImageField(blank=True, upload_to='', verbose_name='до')),
                ('foto_after', models.ImageField(blank=True, upload_to='', verbose_name='после')),
                ('active', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
