# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161120_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.CharField(default='qwe', max_length=255, verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.CharField(default='qwe', max_length=255, verbose_name='время выполнения'),
            preserve_default=False,
        ),
    ]
