# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161120_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_base', models.TextField()),
                ('text_welcome', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to=b'')),
                ('contact', models.TextField()),
            ],
        ),
    ]
