# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Тексты',
                'verbose_name': 'Текст',
            },
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директор'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AlterField(
            model_name='director',
            name='contact',
            field=models.TextField(verbose_name='контакты'),
        ),
        migrations.AlterField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='text_base',
            field=models.TextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='director',
            name='text_welcome',
            field=models.TextField(verbose_name='Текст приветствия'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='active',
            field=models.BooleanField(verbose_name='На главной?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
