# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170124_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Категория',
                'verbose_name': 'Категория',
            },
        ),
        migrations.AddField(
            model_name='maintext',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='maintext',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintext',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='maintext',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.TextCategory'),
            preserve_default=False,
        ),
    ]
