# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-27 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170127_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintext',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='textcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
